version: '3'

services:
  server:
    build: ./server
    ports:
      - "50051:50051"
    restart: always

  client:
    build: ./client
    depends_on:
      - server
    stdin_open: true  
    tty: true
