# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: key_value_store.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15key_value_store.proto\"(\n\nPutRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\x1d\n\x0bPutResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"\x19\n\nGetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\",\n\x0bGetResponse\x12\r\n\x05value\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\"\x1c\n\rDeleteRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\" \n\x0e\x44\x65leteResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2~\n\rKeyValueStore\x12 \n\x03Put\x12\x0b.PutRequest\x1a\x0c.PutResponse\x12 \n\x03Get\x12\x0b.GetRequest\x1a\x0c.GetResponse\x12)\n\x06\x44\x65lete\x12\x0e.DeleteRequest\x1a\x0f.DeleteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'key_value_store_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_PUTREQUEST']._serialized_start=25
  _globals['_PUTREQUEST']._serialized_end=65
  _globals['_PUTRESPONSE']._serialized_start=67
  _globals['_PUTRESPONSE']._serialized_end=96
  _globals['_GETREQUEST']._serialized_start=98
  _globals['_GETREQUEST']._serialized_end=123
  _globals['_GETRESPONSE']._serialized_start=125
  _globals['_GETRESPONSE']._serialized_end=169
  _globals['_DELETEREQUEST']._serialized_start=171
  _globals['_DELETEREQUEST']._serialized_end=199
  _globals['_DELETERESPONSE']._serialized_start=201
  _globals['_DELETERESPONSE']._serialized_end=233
  _globals['_KEYVALUESTORE']._serialized_start=235
  _globals['_KEYVALUESTORE']._serialized_end=361
# @@protoc_insertion_point(module_scope)
